# Generated by Django 5.0.6 on 2024-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='uploads/')),
                ('dst_image', models.ImageField(upload_to='uploads/')),
                ('src_image', models.ImageField(upload_to='uploads/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output/')),
            ],
        ),
    ]
